name: Release test pre-release version

on: issue_comment

jobs:
  check_comments:
    name: Check comments for /test
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - name: Check command
        id: command
        uses: xt0rted/slash-command-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          command: pre-release
          reaction: "true"
          reaction-type: "eyes"
          allow-edits: "false"
          permission-level: write
      - name: Act on the command
        run: echo "The command was '${{ steps.command.outputs.command-name }}' with arguments '${{ steps.command.outputs.command-arguments }}'"
