name: Release test pre-release version

on:
  repository_dispatch:
    types: [pre-release-command]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.pull_request.merge_commit_sha }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install deps
        run: |
          python -m pip install pip --upgrade
          pip install poetry
          pip install githubrelease
          pip install autopub
          pip install httpx
      - name: Check if release exists
        id: check_release
        run: |
          set +e
          echo ::set-output name=release::$(autopub check)
      - name: Prepare pre-release version
        if: steps.check_release.outputs.release == ''
        run: |
          autopub prepare
          poetry version prerelease
          poetry version
